[package]
name = "viper"
version = "0.1.0"
edition = "2021"

[dependencies]
duchess = { path = "../.." }

[build-dependencies]
ureq = "2.1"

[features]
jni_1_6 = ["duchess/jni_1_6"]
jni_1_8 = ["duchess/jni_1_8"]
